name: myapp
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.17.0 
  http: ^0.13.6  # Asegúrate de usar la última versión disponible

dev_dependencies:
  dwds: ^11.1.0 # Agregado para soporte de herramientas de desarrollo en web
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Para añadir activos personalizados o fuentes, puedes descomentar y añadir
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
